
# Alert for populating the 'tenx_pure_dml' sourcetype and 'tenx_dml' collection needed
# by the 10x application to decode 10x encoded data.
#
# See savedsearches.conf for more info.
#
[tenx_dml_to_kv]
is_custom = 1
label = Fill KV store from DML
payload_format = json
disabled = 0
python.version = python3
icon_path = kv_alert.png
