#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 1
label = 10x for Splunk

[launcher]
author = Log10x
description = Log10x log optimization for Splunk
version = 0.9.0

[triggers]
reload.tenx_config = simple

[package]
id = tenx-for-splunk
