
# Defines a kv store collection utilized by 10x to decode encoded events.
#
# For more details, see:
# macros.conf - The definitions of the macros utilizing the 'tenx_dml' collection
# savedsearches.conf - Details about how the 'tenx_dml' collection gets populated.
# transforms.conf - The definition of the lookup on the 'tenx_dml' collection
#
[tenx_dml]
field.pattern_hash = string
field.pattern = string
field.pattern_parts = array
field.part_0 = string
field.pattern_terminator = string
field.timestamp_format = string
