
# Macro for decoding 10x encoded events.
# The macro utilizes the 'tenx_dml' collection and 'tenx-dml-lookup' lookup to get the decoded values
# matching the encoded data, and then tailors the data together via the 'mvzip' SPL command.
#
# After decoding, removed the utilized tenx fields with the SPL 'fields' command to avoid streaming
# unnecessary data.
#
# For more details, see:
# collections.conf - The definition of the 'tenx_dml' collection.
# savedsearches.conf - Details about how the 'tenx_dml' collection gets populated.
# transforms.conf - The definition of the 'tenx-dml-lookup' lookup.
# 
[tenx-inflate]
definition = makemv delim="," tenx_vars | lookup tenx-dml-lookup _key AS tenx_hash OUTPUT part_0 AS tenx_part_0, pattern_parts AS tenx_log_parts, pattern_terminator AS tenx_log_term, timestamp_format AS tenx_ts_f | eval tenx_ts_sec=if(tenx_var_0 > 10000000000000, tenx_var_0 / 1000000000, tenx_var_0 / 1000) | eval _raw=if(isnull(tenx_log_term), _raw, if(tenx_ts_f == "", if(isnull(tenx_var_0), tenx_log_term, mvjoin(mvappend(tenx_part_0, tenx_var_0, mvzip(tenx_log_parts,tenx_vars,""), tenx_log_term),"")), replace(mvjoin(mvappend(mvzip(tenx_log_parts,tenx_vars,""), tenx_log_term),""), "__TENX_TS__", strftime(tenx_ts_sec, tenx_ts_f)))) | fields  - tenx_hash, tenx_log_parts, tenx_log_term, tenx_ts_f, tenx_part_0, tenx_var_0, tenx_vars, tenx_ts_sec

# Same as the 'tenx-inflate' macro, but without the removal of tenx fields, allows for easier debugging.
#
[tenx-inflate-debug]
definition = makemv delim="," tenx_vars | lookup tenx-dml-lookup _key AS tenx_hash OUTPUT part_0 AS tenx_part_0, pattern_parts AS tenx_log_parts, pattern_terminator AS tenx_log_term, timestamp_format AS tenx_ts_f | eval tenx_ts_sec=if(tenx_var_0 > 10000000000000, tenx_var_0 / 1000000000, tenx_var_0 / 1000) | eval _raw=if(isnull(tenx_log_term), _raw, if(tenx_ts_f == "", if(isnull(tenx_var_0), tenx_log_term, mvjoin(mvappend(tenx_part_0, tenx_var_0, mvzip(tenx_log_parts,tenx_vars,""), tenx_log_term),"")), replace(mvjoin(mvappend(mvzip(tenx_log_parts,tenx_vars,""), tenx_log_term),""), "__TENX_TS__", strftime(tenx_ts_sec, tenx_ts_f))))

# Macro for displaying a message as a search result.
# Simply appends a new synthetic event to an empty search.
#
[tenx-message(1)]
args = term
definition = search tenxsearchstringthatneverhits | append [| makeresults | eval _raw="$term$"]
