
# A periodic search job which is responsible for automatically filling the 'pure' dml sourcetype
# and the tenx_dml collection with the necessary data for 10x decoding.
#
# Input -
# The 'tenx_dml_raw_json' sourcetype, which should contain json events matching the structure of
# {"templateHash":"<hash_value>", "template":"<template_value>"}
#
# Output -
# The 'tenx_pure_dml' sourcetype, which will contain a simplified non-json string events with
# a structure "<hash_value> <modified_template_value>"
# This sourcetype is used for finding the hashes matching specific user searches, so <modified_template_value>
# is the original <template_value>, but with new-lines and the 10x variable separators removed,
# as those don't add any useful information for the search.
#
# Output -
# The 'tenx_dml' collection, which will contain a modified structure of the <template_value> which
# the 10x decoding macro utilizes when decoding events.
#
# For more details, see:
# tenx_dml_to_kv.py - The python code invoked by this alert which does all the above input -> output.
# alert_actions.conf - The definition of the alert action invoking the python code.
# collections.conf - The definition of the 'tenx_dml' collection.
# macros.conf - The definition of the decoding macro.
# props.conf - The definitions of the sourcetypes.
# transforms.conf - The definition of the lookup on the 'tenx_dml' collection.
# 
[Consume KV]
action.tenx_dml_to_kv = 1
alert.digest_mode = 1
alert.expires = 10h
alert.suppress = 0
alert.track = 0
cron_schedule = */2 * * * *
dispatch.earliest_time = -3m
dispatch.latest_time = now
enableSched = 1
request.ui_dispatch_app = tenx-for-splunk
request.ui_dispatch_view = tenx-for-splunk
search = index=tenx_dml sourcetype=tenx_dml_raw_json
counttype = number of events
quantity = 0
relation = greater than
