
# BNF definition for the tenxsearch generating python command.
# See tenxsearch.py for more details.
#
[tenxsearch-command]
syntax = tenxsearch [searchstring=<string>]
shortdesc = Command to wrap a standard splunk search with 10x decoding capabilities.
usage = public
