
# General configuration of the 10x app.
# 
[config]

# Defines the destination index/sourcetype of the pure processed patterns
# See props.conf for more info.
#
dest_dml_index = main
dml_source_type = tenx_dml_pure

# Defines the name of the kv store used by the 10x app to decode events.
# See collections.conf for more info.
#
collection_name = tenx_dml

# Defines information about how the 10x template is utilized for decoding events.
# See tenx_dml_to_kv.py and macros.conf for more info.
#
timestamp_placeholder = __TENX_TS__
variable_separator = $

# Defines the extraction on encoded events which allows the 10x app to decode them.
# See macros.conf and transforms.conf for more info.
#
tenx_extraction_name=REPORT-tenx
tenx_extraction=tenx-hash-vars-extraction
