
# Expose the tenx_search endpoint via Splunkweb on port 8000 and splunkd on port 8089
#
# See restmap.conf for more info.
#
[expose:tenx-search]
methods = POST
pattern = tenx-search

# Expose the tenx_config endpoint via Splunkweb on port 8000 and splunkd on port 8089
#
# See restmap.conf for more info.
#
[expose:tenx-config]
methods = GET,POST,DELETE
pattern = tenx-config
